### ISSUE TITLE
Remote Decks Bug

### ISSUE THREAD

**Issue by PBP34** [AnKing-Memberships/anki-remote-decks#5] opened 2023-02-10 22:02 UTC
## Which add-on is this about?
REMOTE DECKS V2.0 

#### Problem description
Whenever I sync my remote deck, every card that has an image on the top portion redownloads instead of being treated as a card that I have already done. For instance:
![image](https://user-images.githubusercontent.com/125093822/218206889-81111588-fc7c-4339-9af0-fcc0df17ae32.png)

A card like what is shown above resyncs as a new cards every time I sync my deck even though I have already done that card multiple times.

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*
X I have restarted anki
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment] 2023-02-10 23:35
I have a suspicion as to why this may be happening. In the meantime, it may be helpful to just add some text above the image. We can look into this

**Comment by AnKing-Forrest** [comment] 2023-03-06 04:25
We have people working on this now. In the meantime, try adding text above the image on all of these cards. Something like "Image" so that when the add-on program is reaching out to the remote deck, it is encountering a string of letters rather than an image to mark the start of the card. Let me know if that doesn't work and we'll come up with some other workarounds until this issue is resolved at the level of the code.

**Comment by abdnh** [comment] 2023-03-08 02:13
I believe this is caused by Google Docs changing the URL of the image and the add-on relying on the URL to derive the image name. As a result, the the contents of the first field changes, making the add-on add a new note.
@AnKingMed do you have a different opinion?

**Comment by AnKingMed** [comment] 2023-03-08 02:28
If that's the case I think I'm ok just leaving this bug. We should just add it to the readme as a "known bug"

**Comment by PBP34** [comment] 2023-03-08 02:29
How would a user work around the bug? Just don't add any images to cards?

**Comment by AnKingMed** [comment] 2023-03-08 02:31
I'd try adding text before the image

**Comment by PBP34** [comment] 2023-03-08 02:32
I've done that and it didn't change anything for me but maybe I am doing
something wrong?

**Comment by AnKingMed** [comment] 2023-03-08 02:35
Hmm.. in this case @abdnh do you think it'd be possible to ignore the img html when matching notes? Or is that not possible?

**Comment by AnKingMed** [comment] 2023-03-08 02:35
You can ask @RisingOrange if needed. He's the one that originally modified this add-on

**Comment by abdnh** [comment] 2023-03-08 04:01
The issue can be properly fixed by deriving the filename from the actual contents of the image instead of its URL. I can push an update.

**Closed as completed** 2023-03-12 14:08 UTC
Labels: bug
